// Bundle the BullMQ worker entrypoint into a single self-contained CJS file
// (dist/worker.cjs) so it can run with `node dist/worker.cjs` without a
// node_modules tree — the same Docker image serves both the web server and the
// worker (via command override).
//
// esbuild resolves the `@/*` path alias from tsconfig.json automatically.
// Optional native addons (msgpackr's accelerator, postgres/sqlite native
// bindings) are marked external; the pure-JS fallbacks are used at runtime.
import { build } from "esbuild";

const external = [
  "msgpackr-extract",
  "@msgpackr-extract/*",
  "pg-native",
  "better-sqlite3",
  "sql.js",
  "bufferutil",
  "utf-8-validate",
];

await build({
  entryPoints: ["src/worker.ts"],
  outfile: "dist/worker.cjs",
  bundle: true,
  platform: "node",
  target: "node22",
  format: "cjs",
  sourcemap: true,
  minify: false,
  external,
  logLevel: "info",
  banner: {
    js: "/* oh-my-prompt worker — generated by scripts/build-worker.mjs, do not edit */",
  },
});

console.log("Worker bundled -> dist/worker.cjs");
